### ISSUE TITLE
multiple TableViews for "Device List"

### ISSUE THREAD

**Issue by gotoplanb** [nielubowicz/CheckItOut#1]
It would be nice to have three TableViews under "Device List"

First would be "Devices I have"

Second would be "Available devices"

Third would be "Unavailable devices"

**Comment by nielubowicz** [comment]
That's three TableViews

**Comment by nielubowicz** [comment]
Added a dataSource object that creates three sections (each of which disappears when empty):
1. My Devices
2. Checked Out Devices
3. Available Devices

Should be addressed by https://github.com/nielubowicz/CheckItOut/commit/60235647bcbc71d8428118250b02cd9be075184e

Order of sections is easy to change if you have any design objections.
